---
- name: home skel dirs
  file:
    path: "~/{{ item }}"
    state: directory
  with_items:
    - "dev"
    - "tmp"
    - "bin"

- name: git clone brainstorm dotfiles
  git:
    repo: https://github.com/brainstorm/dotfiles
    dest: ~/dev/dotfiles
    depth: 1

- name: setup dotfiles themselves at $HOME
  command: ~/dev/dotfiles/install
