---
# necessary steps to configure the role

- name: install base condarc
  become: no
  copy: src={{ item }} dest="~/.{{ item }}"
  with_items:
    - condarc
  when: miniconda_add_condarc

- name: add miniconda to the PATH
  become: no
  lineinfile:
    dest: "{{ miniconda_rcfile }}"
    line: export PATH={{ miniconda_home }}/bin:$PATH
    state: present
  when: miniconda_modify_path

- name: create environments
  become: no

  with_items: miniconda_environments
  debug:
    var: item.python_version
  
  #msg: "{{ miniconda_home }}/bin/conda create --yes -q -n item[env_name] python=item[python_version] creates={{ miniconda_home }}/envs/item['env_name']"
  #shell: "{{ miniconda_home }}/bin/conda create --yes -q -n item[env_name] python=item[python_version] creates={{ miniconda_home }}/envs/item[env_name]"

  when: miniconda_installed | success
